---

- hosts: prod_gaming_hosts
  sudo: yes
#  vars:
#    ansible_ssh_private_key_file: "{{ key1 }}"
  tasks:
    - name: Go to metrics time travel
      command: cd ~/metrics-tt
    - name: shift dem metrics
      command: ./shift_all.sh 1571452200 shiftinfo.csv > shifted.log
    - name: go to event time travel
      command: cd timetravel/
    - name: shift dem events
      command: nohup ./shift_all_throttled.sh 1571452200 episode_offsets.csv > log/shifted.log &